development:
  adapter: postgresql
  encoding: utf8
  database: invoice_creator_development
  pool: 5
  username: 
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: invoice_creator_test
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: invoice_creator_production
  pool: 5
  username: 
  password: